language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: Fabien-Vauclin-github
# command to run tests
script:
  - pytest -v --cov
  #- sonar-scanner
  - coveralls